# Generated by Django 6.0.3 on 2026-04-07 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='usuario_conclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes_concluidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditoriaexclusao',
            name='tipo_movimento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (NF)'), ('SAIDA', 'Saída (Paciente)'), ('BAIXA', 'Baixa (Descarte)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
