# Generated by Django 6.0.3 on 2026-04-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_auditoriaexclusao_tipo_movimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaexclusao',
            name='tipo_movimento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (NF)'), ('SAIDA', 'Saída (Paciente)'), ('BAIXA', 'Baixa (Descarte)'), ('MANUTENCAO', 'Manutenção')], max_length=15),
        ),
    ]
