# Generated by Django 6.0.3 on 2026-06-10 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_auditoriaexclusao_tipo_movimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaexclusao',
            name='tipo_movimento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (NF)'), ('SAIDA', 'Saída (Paciente)'), ('BAIXA', 'Baixa (Descarte)'), ('MANUTENCAO', 'Manutenção'), ('TRANSFERENCIA', 'Transferência')], max_length=15),
        ),
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ARMAZENAMENTO', 'Armazenamento (Almoxarifado/Depósito)'), ('DISTRIBUICAO', 'Distribuição (Setor/Farmácia)')], default='ARMAZENAMENTO', max_length=20)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='estoque.empresa')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='baixa',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='estoque.localestoque'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='estoque.localestoque'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='estoque.localestoque'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='estoque.localestoque'),
        ),
        migrations.AddField(
            model_name='saida',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='estoque.localestoque'),
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together={('produto', 'local')},
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.empresa')),
                ('local_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='estoque.localestoque')),
                ('local_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='estoque.localestoque')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.transferencia')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='estoque.transferencia')),
            ],
        ),
    ]
